### ISSUE TITLE
allowedExtensions doesn't work in Android

### ISSUE THREAD

**Issue by piratkin** [andyduke/filesystem_picker#25]
I'm trying to open files with the `.cpp/.hpp` extension on an android device, 
but `FilesystemPicker` hides them from the directory, 
if i rename them to `.png/.jpeg./.Djavu` ..., 
they are visible. 
In the case of building a Windows application, 
everything works well.

```dart
...
class OpenFileDialog {
  Future<String?> open(BuildContext context) async {
    const String title = 'Open file';
    const selectMode = FileTileSelectMode.wholeTile;
    final rootDirectory = await homeDirectory();
    if (rootDirectory == null) {
      showErrorMessage("Can't find the path to home directory!!!",
          context: context);
      return null;
    }
    return await FilesystemPicker.open(
      title: title,
      context: context,
      rootName: "root",
      rootDirectory: rootDirectory,
      fsType: FilesystemType.file,
      //allowedExtensions: null,
      allowedExtensions: ['.cpp', '.hpp', '.cc', '.hh', '.c', '.h'],
      folderIconColor: Colors.blue,
      fileTileSelectMode: selectMode,
      requestPermission: () async {
        if (Platform.isAndroid || Platform.isIOS) {
          final status = await Permission.storage.request();
          return status.isGranted;
        }
        return true;
      },
    );
  }
}
```

Android version: 11
kernel version: 4.14.113-21059290

When I try to set any value to the variable `allowedExtensions`, in this case all files disappear in my selection, only directories are visible.

```sh
PS C:\arch\work\apps\test> flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.17763.1879], locale ru-RU)
    • Flutter version 2.0.6 at c:\arch\work\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.1879]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

Pub packages:

```yaml
name: test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.1
  permission_handler: ^7.1.0
  filesystem_picker: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
