### ISSUE TITLE
Can't see files created by other app

### ISSUE THREAD

**Issue by daybson** [andyduke/filesystem_picker#30]
My app creates a file in /Downloads directory.
The user can load this file again and retrieve the data (works like an offline backup).

Whoever, I start noticing that files created using an old version of the app weren't being displayed.
And they exists in the /Downloads directory.

The only files the app can 'see' are that which were generated by the new version.

I'm using Android emulator, Android 11
[Video demo](https://youtu.be/buYXNbsaYro)

Help please?! >_<

minSdkVersion 21
targetSdkVersion 30
compileSdkVersion 30

```
 result = await FilesystemPicker.open(
        rootName: directory.path,
        title: 'Restaurar backup',
        context: Get.context,
        allowedExtensions: ['.3dit'],
        fileTileSelectMode: FileTileSelectMode.wholeTile,
        rootDirectory: directory,
        fsType: FilesystemType.file,
        requestPermission: () async =>
            await Permission.storage.request().isGranted,
        folderIconColor: Colors.amber,
      );
```

```
dependencies:
  flutter:
    sdk: flutter
  downloads_path_provider: ^0.1.0
  dropdown_search: ^0.6.3
  encrypt: ^5.0.1
  filesystem_picker: ^1.0.4  
  firebase_core: ^1.6.0
  firebase_remote_config: ^0.10.0+5
  flutter_screenutil: ^2.3.1
  flutter_spinbox: ^0.5.4
  get: ^4.3.8
  google_mobile_ads: ^0.13.4
  image_picker: ^0.8.3+2
  launch_review: ^3.0.1
  open_file: ^3.2.1
  package_info: ^2.0.2 
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_macos: ^2.0.2
  path_provider_windows: ^2.0.3
  pdf: ^3.5.0
  permission_handler: ^8.1.4+2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  sqflite_sqlcipher: ^2.0.0
  url_launcher: ^6.0.10
  uuid: ^3.0.4
```

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.19043.1165], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)  
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.60.0)
[√] Connected device (4 available)

@andyduke
